/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "test.c"
/* Header for class com_scnu_lwg_jni_JniTest */

#ifndef _Included_com_scnu_lwg_jni_JniTest
#define _Included_com_scnu_lwg_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scnu_lwg_jni_JniTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_scnu_lwg_jni_JniTest_add
  (JNIEnv * env, jobject j, jint x, jint y){
    test();
    fflush(stdout);
    return x + y;
  }

/*
 * Class:     com_scnu_lwg_jni_JniTest
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_scnu_lwg_jni_JniTest_sub
  (JNIEnv * env, jobject j, jint x, jint y){
    return x - y;
  }

/*
 * Class:     com_scnu_lwg_jni_JniTest
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_scnu_lwg_jni_JniTest_plus
  (JNIEnv * env, jobject j, jint x, jint y){
    return x * y;
  }
#ifdef __cplusplus
}
#endif
#endif
