# 项目端口
server:
  #连接超时，单位为毫秒，-1永不超时
  connection-timeout: 60000
  #设置tomcat参数
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    min-spare-threads: 10
    #最大220个并发，可以达到不丢包（可以自己实测），默认为200。
    max-threads: 220
    #配置访问路径，默认为/
    #servlet:
    #context-path: /index/main

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #create user 'lwgtest'@'%' identified by '!@#Lwgtest2021';#创建用户
    url: jdbc:mysql://39.96.89.236:3306/lwg?characterEncoding=utf8
    username: lwgtest
    password: '!@#Lwgtest2021'
    #max active
    maxActive: 20
    #init size
    initialSize: 1
    #max wait time
    maxWait: 60000
    #open PSCache，and set single PSCache size
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #via connectionProperties open mergeSql, slow sql record
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #configuration monitor statistics filters，monitor page statistics sql,'wall' use in firewall
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

#配置日志文件参数
logging:
  file:
    path: classpath:/logs/admin.log
  level:
    org:
      springframework: debug
    hibernate: debug



# default user configuration
lwg:
  users:
    - appId: 123456
      appSecret: 123
    - appId: test
      appSecret: test123

# mqtt config
mqtt:
  broker: tcp://39.96.89.236:1883 #url
  start: true #start server
  url: https://www.kinsanity.cn/lwg/humiture/send
  lib:
    crypto: '/root/hjf/lwg/package/lib/libwbcrypto.so'
    jni: '/root/hjf/lwg/package/lib/libmain.so'
  wb:
    filepath: '/root/hjf/lwg/package/lib/wb_sm4.key'
# okhttp
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300