# tomcat
server:
  # 端口
  port: ${LWG_SERVER_PORT:9800}
  #连接超时，单位为毫秒，-1永不超时
  connection-timeout: 60000
  #设置tomcat参数
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    min-spare-threads: 10
    #最大220个并发，可以达到不丢包（可以自己实测），默认为200。
    max-threads: 220

# mqtt
mqtt:
  broker: ${LWG_MQTT_BROKER:tcp://192.168.13.223:11883} #url
  username: ${LWG_MQTT_USERNAME:lwg}
  password: ${LWG_MQTT_PASSWORD:lwgscnu2021}
  topics: ${LWG_MQTT_TOPICS:WifiDHT/+/DHT11,LWG/MQTT/TOPIC}
  start: ${LWG_MQTT_START:true} #start consumer server
  url: ${LWG_MQTT_URL:https://www.kinsanity.cn}


# okhttp
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
